/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthLoginUser model module.
 * @module model/AuthLoginUser
 * @version 0.2.4
 */
class AuthLoginUser {
    /**
     * Constructs a new <code>AuthLoginUser</code>.
     * @alias module:model/AuthLoginUser
     */
    constructor() { 
        
        AuthLoginUser.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthLoginUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthLoginUser} obj Optional instance to populate.
     * @return {module:model/AuthLoginUser} The populated <code>AuthLoginUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthLoginUser();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
AuthLoginUser.prototype['_id'] = undefined;

/**
 * @member {String} name
 */
AuthLoginUser.prototype['name'] = undefined;

/**
 * @member {String} role
 */
AuthLoginUser.prototype['role'] = undefined;






export default AuthLoginUser;

