/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AuthLoginUser from './AuthLoginUser';

/**
 * The AuthLoginResponse model module.
 * @module model/AuthLoginResponse
 * @version 0.2.4
 */
class AuthLoginResponse {
    /**
     * Constructs a new <code>AuthLoginResponse</code>.
     * @alias module:model/AuthLoginResponse
     */
    constructor() { 
        
        AuthLoginResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthLoginResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthLoginResponse} obj Optional instance to populate.
     * @return {module:model/AuthLoginResponse} The populated <code>AuthLoginResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthLoginResponse();

            if (data.hasOwnProperty('user')) {
                obj['user'] = AuthLoginUser.constructFromObject(data['user']);
            }
            if (data.hasOwnProperty('validated')) {
                obj['validated'] = ApiClient.convertToType(data['validated'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/AuthLoginUser} user
 */
AuthLoginResponse.prototype['user'] = undefined;

/**
 * @member {Boolean} validated
 */
AuthLoginResponse.prototype['validated'] = undefined;






export default AuthLoginResponse;

