/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.3.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MetaPage from './MetaPage';

/**
 * The IndexIndexListResponse model module.
 * @module model/IndexIndexListResponse
 * @version 0.3.3
 */
class IndexIndexListResponse {
    /**
     * Constructs a new <code>IndexIndexListResponse</code>.
     * @alias module:model/IndexIndexListResponse
     */
    constructor() { 
        
        IndexIndexListResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IndexIndexListResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IndexIndexListResponse} obj Optional instance to populate.
     * @return {module:model/IndexIndexListResponse} The populated <code>IndexIndexListResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IndexIndexListResponse();

            if (data.hasOwnProperty('list')) {
                obj['list'] = ApiClient.convertToType(data['list'], [Object]);
            }
            if (data.hasOwnProperty('page')) {
                obj['page'] = MetaPage.constructFromObject(data['page']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Object>} list
 */
IndexIndexListResponse.prototype['list'] = undefined;

/**
 * @member {module:model/MetaPage} page
 */
IndexIndexListResponse.prototype['page'] = undefined;






export default IndexIndexListResponse;

