/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.3.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IndexAnalyzeResponseToken from './IndexAnalyzeResponseToken';

/**
 * The IndexAnalyzeResponse model module.
 * @module model/IndexAnalyzeResponse
 * @version 0.3.3
 */
class IndexAnalyzeResponse {
    /**
     * Constructs a new <code>IndexAnalyzeResponse</code>.
     * @alias module:model/IndexAnalyzeResponse
     */
    constructor() { 
        
        IndexAnalyzeResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>IndexAnalyzeResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/IndexAnalyzeResponse} obj Optional instance to populate.
     * @return {module:model/IndexAnalyzeResponse} The populated <code>IndexAnalyzeResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IndexAnalyzeResponse();

            if (data.hasOwnProperty('tokens')) {
                obj['tokens'] = ApiClient.convertToType(data['tokens'], [IndexAnalyzeResponseToken]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/IndexAnalyzeResponseToken>} tokens
 */
IndexAnalyzeResponse.prototype['tokens'] = undefined;






export default IndexAnalyzeResponse;

