/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AggregationHistogramBound from './AggregationHistogramBound';

/**
 * The MetaAggregationHistogram model module.
 * @module model/MetaAggregationHistogram
 * @version 0.2.4
 */
class MetaAggregationHistogram {
    /**
     * Constructs a new <code>MetaAggregationHistogram</code>.
     * @alias module:model/MetaAggregationHistogram
     */
    constructor() { 
        
        MetaAggregationHistogram.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetaAggregationHistogram</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetaAggregationHistogram} obj Optional instance to populate.
     * @return {module:model/MetaAggregationHistogram} The populated <code>MetaAggregationHistogram</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetaAggregationHistogram();

            if (data.hasOwnProperty('extended_bounds')) {
                obj['extended_bounds'] = AggregationHistogramBound.constructFromObject(data['extended_bounds']);
            }
            if (data.hasOwnProperty('field')) {
                obj['field'] = ApiClient.convertToType(data['field'], 'String');
            }
            if (data.hasOwnProperty('hard_bounds')) {
                obj['hard_bounds'] = AggregationHistogramBound.constructFromObject(data['hard_bounds']);
            }
            if (data.hasOwnProperty('interval')) {
                obj['interval'] = ApiClient.convertToType(data['interval'], 'Number');
            }
            if (data.hasOwnProperty('keyed')) {
                obj['keyed'] = ApiClient.convertToType(data['keyed'], 'Boolean');
            }
            if (data.hasOwnProperty('min_doc_count')) {
                obj['min_doc_count'] = ApiClient.convertToType(data['min_doc_count'], 'Number');
            }
            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/AggregationHistogramBound} extended_bounds
 */
MetaAggregationHistogram.prototype['extended_bounds'] = undefined;

/**
 * @member {String} field
 */
MetaAggregationHistogram.prototype['field'] = undefined;

/**
 * @member {module:model/AggregationHistogramBound} hard_bounds
 */
MetaAggregationHistogram.prototype['hard_bounds'] = undefined;

/**
 * @member {Number} interval
 */
MetaAggregationHistogram.prototype['interval'] = undefined;

/**
 * @member {Boolean} keyed
 */
MetaAggregationHistogram.prototype['keyed'] = undefined;

/**
 * @member {Number} min_doc_count
 */
MetaAggregationHistogram.prototype['min_doc_count'] = undefined;

/**
 * @member {Number} offset
 */
MetaAggregationHistogram.prototype['offset'] = undefined;

/**
 * @member {Number} size
 */
MetaAggregationHistogram.prototype['size'] = undefined;






export default MetaAggregationHistogram;

