/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MetaVersionResponse model module.
 * @module model/MetaVersionResponse
 * @version 0.2.7
 */
class MetaVersionResponse {
    /**
     * Constructs a new <code>MetaVersionResponse</code>.
     * @alias module:model/MetaVersionResponse
     */
    constructor() { 
        
        MetaVersionResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetaVersionResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetaVersionResponse} obj Optional instance to populate.
     * @return {module:model/MetaVersionResponse} The populated <code>MetaVersionResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetaVersionResponse();

            if (data.hasOwnProperty('branch')) {
                obj['branch'] = ApiClient.convertToType(data['branch'], 'String');
            }
            if (data.hasOwnProperty('build')) {
                obj['build'] = ApiClient.convertToType(data['build'], 'String');
            }
            if (data.hasOwnProperty('build_date')) {
                obj['build_date'] = ApiClient.convertToType(data['build_date'], 'String');
            }
            if (data.hasOwnProperty('commit_hash')) {
                obj['commit_hash'] = ApiClient.convertToType(data['commit_hash'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} branch
 */
MetaVersionResponse.prototype['branch'] = undefined;

/**
 * @member {String} build
 */
MetaVersionResponse.prototype['build'] = undefined;

/**
 * @member {String} build_date
 */
MetaVersionResponse.prototype['build_date'] = undefined;

/**
 * @member {String} commit_hash
 */
MetaVersionResponse.prototype['commit_hash'] = undefined;

/**
 * @member {String} version
 */
MetaVersionResponse.prototype['version'] = undefined;






export default MetaVersionResponse;

