/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MetaHit from './MetaHit';
import MetaTotal from './MetaTotal';

/**
 * The MetaHits model module.
 * @module model/MetaHits
 * @version 0.2.4
 */
class MetaHits {
    /**
     * Constructs a new <code>MetaHits</code>.
     * @alias module:model/MetaHits
     */
    constructor() { 
        
        MetaHits.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetaHits</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetaHits} obj Optional instance to populate.
     * @return {module:model/MetaHits} The populated <code>MetaHits</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetaHits();

            if (data.hasOwnProperty('hits')) {
                obj['hits'] = ApiClient.convertToType(data['hits'], [MetaHit]);
            }
            if (data.hasOwnProperty('max_score')) {
                obj['max_score'] = ApiClient.convertToType(data['max_score'], 'Number');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = MetaTotal.constructFromObject(data['total']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/MetaHit>} hits
 */
MetaHits.prototype['hits'] = undefined;

/**
 * @member {Number} max_score
 */
MetaHits.prototype['max_score'] = undefined;

/**
 * @member {module:model/MetaTotal} total
 */
MetaHits.prototype['total'] = undefined;






export default MetaHits;

