/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MetaIndexAnalysis from './MetaIndexAnalysis';

/**
 * The MetaIndexSettings model module.
 * @module model/MetaIndexSettings
 * @version 0.2.4
 */
class MetaIndexSettings {
    /**
     * Constructs a new <code>MetaIndexSettings</code>.
     * @alias module:model/MetaIndexSettings
     */
    constructor() { 
        
        MetaIndexSettings.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetaIndexSettings</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetaIndexSettings} obj Optional instance to populate.
     * @return {module:model/MetaIndexSettings} The populated <code>MetaIndexSettings</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetaIndexSettings();

            if (data.hasOwnProperty('analysis')) {
                obj['analysis'] = MetaIndexAnalysis.constructFromObject(data['analysis']);
            }
            if (data.hasOwnProperty('number_of_replicas')) {
                obj['number_of_replicas'] = ApiClient.convertToType(data['number_of_replicas'], 'Number');
            }
            if (data.hasOwnProperty('number_of_shards')) {
                obj['number_of_shards'] = ApiClient.convertToType(data['number_of_shards'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/MetaIndexAnalysis} analysis
 */
MetaIndexSettings.prototype['analysis'] = undefined;

/**
 * @member {Number} number_of_replicas
 */
MetaIndexSettings.prototype['number_of_replicas'] = undefined;

/**
 * @member {Number} number_of_shards
 */
MetaIndexSettings.prototype['number_of_shards'] = undefined;






export default MetaIndexSettings;

