/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.3.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MetaAggregationResponse from './MetaAggregationResponse';
import MetaHits from './MetaHits';
import MetaShards from './MetaShards';

/**
 * The MetaSearchResponse model module.
 * @module model/MetaSearchResponse
 * @version 0.3.3
 */
class MetaSearchResponse {
    /**
     * Constructs a new <code>MetaSearchResponse</code>.
     * @alias module:model/MetaSearchResponse
     */
    constructor() { 
        
        MetaSearchResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetaSearchResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetaSearchResponse} obj Optional instance to populate.
     * @return {module:model/MetaSearchResponse} The populated <code>MetaSearchResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetaSearchResponse();

            if (data.hasOwnProperty('_shards')) {
                obj['_shards'] = MetaShards.constructFromObject(data['_shards']);
            }
            if (data.hasOwnProperty('aggregations')) {
                obj['aggregations'] = ApiClient.convertToType(data['aggregations'], {'String': MetaAggregationResponse});
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('hits')) {
                obj['hits'] = MetaHits.constructFromObject(data['hits']);
            }
            if (data.hasOwnProperty('timed_out')) {
                obj['timed_out'] = ApiClient.convertToType(data['timed_out'], 'Boolean');
            }
            if (data.hasOwnProperty('took')) {
                obj['took'] = ApiClient.convertToType(data['took'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/MetaShards} _shards
 */
MetaSearchResponse.prototype['_shards'] = undefined;

/**
 * @member {Object.<String, module:model/MetaAggregationResponse>} aggregations
 */
MetaSearchResponse.prototype['aggregations'] = undefined;

/**
 * @member {String} error
 */
MetaSearchResponse.prototype['error'] = undefined;

/**
 * @member {module:model/MetaHits} hits
 */
MetaSearchResponse.prototype['hits'] = undefined;

/**
 * @member {Boolean} timed_out
 */
MetaSearchResponse.prototype['timed_out'] = undefined;

/**
 * Time it took to generate the response
 * @member {Number} took
 */
MetaSearchResponse.prototype['took'] = undefined;






export default MetaSearchResponse;

