/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.3.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MetaQuery from './MetaQuery';

/**
 * The MetaBoolQuery model module.
 * @module model/MetaBoolQuery
 * @version 0.3.3
 */
class MetaBoolQuery {
    /**
     * Constructs a new <code>MetaBoolQuery</code>.
     * @alias module:model/MetaBoolQuery
     */
    constructor() { 
        
        MetaBoolQuery.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetaBoolQuery</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetaBoolQuery} obj Optional instance to populate.
     * @return {module:model/MetaBoolQuery} The populated <code>MetaBoolQuery</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetaBoolQuery();

            if (data.hasOwnProperty('filter')) {
                obj['filter'] = ApiClient.convertToType(data['filter'], [MetaQuery]);
            }
            if (data.hasOwnProperty('minimum_should_match')) {
                obj['minimum_should_match'] = ApiClient.convertToType(data['minimum_should_match'], 'Number');
            }
            if (data.hasOwnProperty('must')) {
                obj['must'] = ApiClient.convertToType(data['must'], [MetaQuery]);
            }
            if (data.hasOwnProperty('must_not')) {
                obj['must_not'] = ApiClient.convertToType(data['must_not'], [MetaQuery]);
            }
            if (data.hasOwnProperty('should')) {
                obj['should'] = ApiClient.convertToType(data['should'], [MetaQuery]);
            }
        }
        return obj;
    }


}

/**
 * query, [query1, query2]
 * @member {Array.<module:model/MetaQuery>} filter
 */
MetaBoolQuery.prototype['filter'] = undefined;

/**
 * only for should
 * @member {Number} minimum_should_match
 */
MetaBoolQuery.prototype['minimum_should_match'] = undefined;

/**
 * query, [query1, query2]
 * @member {Array.<module:model/MetaQuery>} must
 */
MetaBoolQuery.prototype['must'] = undefined;

/**
 * query, [query1, query2]
 * @member {Array.<module:model/MetaQuery>} must_not
 */
MetaBoolQuery.prototype['must_not'] = undefined;

/**
 * query, [query1, query2]
 * @member {Array.<module:model/MetaQuery>} should
 */
MetaBoolQuery.prototype['should'] = undefined;






export default MetaBoolQuery;

