/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MetaDateRange model module.
 * @module model/MetaDateRange
 * @version 0.2.7
 */
class MetaDateRange {
    /**
     * Constructs a new <code>MetaDateRange</code>.
     * @alias module:model/MetaDateRange
     */
    constructor() { 
        
        MetaDateRange.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetaDateRange</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetaDateRange} obj Optional instance to populate.
     * @return {module:model/MetaDateRange} The populated <code>MetaDateRange</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetaDateRange();

            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], 'String');
            }
            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} from
 */
MetaDateRange.prototype['from'] = undefined;

/**
 * @member {String} to
 */
MetaDateRange.prototype['to'] = undefined;






export default MetaDateRange;

