/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.3.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MetaAggregationMetric model module.
 * @module model/MetaAggregationMetric
 * @version 0.3.3
 */
class MetaAggregationMetric {
    /**
     * Constructs a new <code>MetaAggregationMetric</code>.
     * @alias module:model/MetaAggregationMetric
     */
    constructor() { 
        
        MetaAggregationMetric.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetaAggregationMetric</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetaAggregationMetric} obj Optional instance to populate.
     * @return {module:model/MetaAggregationMetric} The populated <code>MetaAggregationMetric</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetaAggregationMetric();

            if (data.hasOwnProperty('field')) {
                obj['field'] = ApiClient.convertToType(data['field'], 'String');
            }
            if (data.hasOwnProperty('weight_field')) {
                obj['weight_field'] = ApiClient.convertToType(data['weight_field'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} field
 */
MetaAggregationMetric.prototype['field'] = undefined;

/**
 * Field name to be used for setting weight for primary field for weighted average aggregation
 * @member {String} weight_field
 */
MetaAggregationMetric.prototype['weight_field'] = undefined;






export default MetaAggregationMetric;

