/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MetaMultiMatchQuery model module.
 * @module model/MetaMultiMatchQuery
 * @version 0.2.7
 */
class MetaMultiMatchQuery {
    /**
     * Constructs a new <code>MetaMultiMatchQuery</code>.
     * @alias module:model/MetaMultiMatchQuery
     */
    constructor() { 
        
        MetaMultiMatchQuery.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetaMultiMatchQuery</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetaMultiMatchQuery} obj Optional instance to populate.
     * @return {module:model/MetaMultiMatchQuery} The populated <code>MetaMultiMatchQuery</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetaMultiMatchQuery();

            if (data.hasOwnProperty('analyzer')) {
                obj['analyzer'] = ApiClient.convertToType(data['analyzer'], 'String');
            }
            if (data.hasOwnProperty('boost')) {
                obj['boost'] = ApiClient.convertToType(data['boost'], 'Number');
            }
            if (data.hasOwnProperty('fields')) {
                obj['fields'] = ApiClient.convertToType(data['fields'], ['String']);
            }
            if (data.hasOwnProperty('minimum_should_match')) {
                obj['minimum_should_match'] = ApiClient.convertToType(data['minimum_should_match'], 'Number');
            }
            if (data.hasOwnProperty('operator')) {
                obj['operator'] = ApiClient.convertToType(data['operator'], 'String');
            }
            if (data.hasOwnProperty('query')) {
                obj['query'] = ApiClient.convertToType(data['query'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} analyzer
 */
MetaMultiMatchQuery.prototype['analyzer'] = undefined;

/**
 * @member {Number} boost
 */
MetaMultiMatchQuery.prototype['boost'] = undefined;

/**
 * @member {Array.<String>} fields
 */
MetaMultiMatchQuery.prototype['fields'] = undefined;

/**
 * @member {Number} minimum_should_match
 */
MetaMultiMatchQuery.prototype['minimum_should_match'] = undefined;

/**
 * or(default), and
 * @member {String} operator
 */
MetaMultiMatchQuery.prototype['operator'] = undefined;

/**
 * @member {String} query
 */
MetaMultiMatchQuery.prototype['query'] = undefined;

/**
 * best_fields(default), most_fields, cross_fields, phrase, phrase_prefix, bool_prefix
 * @member {String} type
 */
MetaMultiMatchQuery.prototype['type'] = undefined;






export default MetaMultiMatchQuery;

