/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MetaHTTPResponseError model module.
 * @module model/MetaHTTPResponseError
 * @version 0.2.4
 */
class MetaHTTPResponseError {
    /**
     * Constructs a new <code>MetaHTTPResponseError</code>.
     * @alias module:model/MetaHTTPResponseError
     */
    constructor() { 
        
        MetaHTTPResponseError.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetaHTTPResponseError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetaHTTPResponseError} obj Optional instance to populate.
     * @return {module:model/MetaHTTPResponseError} The populated <code>MetaHTTPResponseError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetaHTTPResponseError();

            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} error
 */
MetaHTTPResponseError.prototype['error'] = undefined;






export default MetaHTTPResponseError;

