/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MetaPrefixQuery model module.
 * @module model/MetaPrefixQuery
 * @version 0.2.7
 */
class MetaPrefixQuery {
    /**
     * Constructs a new <code>MetaPrefixQuery</code>.
     * @alias module:model/MetaPrefixQuery
     */
    constructor() { 
        
        MetaPrefixQuery.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetaPrefixQuery</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetaPrefixQuery} obj Optional instance to populate.
     * @return {module:model/MetaPrefixQuery} The populated <code>MetaPrefixQuery</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetaPrefixQuery();

            if (data.hasOwnProperty('boost')) {
                obj['boost'] = ApiClient.convertToType(data['boost'], 'Number');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} boost
 */
MetaPrefixQuery.prototype['boost'] = undefined;

/**
 * You can speed up prefix queries using the index_prefixes mapping parameter.
 * @member {String} value
 */
MetaPrefixQuery.prototype['value'] = undefined;






export default MetaPrefixQuery;

