/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.3.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MetaIndexSettings from './MetaIndexSettings';
import MetaMappings from './MetaMappings';

/**
 * The MetaTemplateTemplate model module.
 * @module model/MetaTemplateTemplate
 * @version 0.3.3
 */
class MetaTemplateTemplate {
    /**
     * Constructs a new <code>MetaTemplateTemplate</code>.
     * @alias module:model/MetaTemplateTemplate
     */
    constructor() { 
        
        MetaTemplateTemplate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetaTemplateTemplate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetaTemplateTemplate} obj Optional instance to populate.
     * @return {module:model/MetaTemplateTemplate} The populated <code>MetaTemplateTemplate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetaTemplateTemplate();

            if (data.hasOwnProperty('mappings')) {
                obj['mappings'] = MetaMappings.constructFromObject(data['mappings']);
            }
            if (data.hasOwnProperty('settings')) {
                obj['settings'] = MetaIndexSettings.constructFromObject(data['settings']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/MetaMappings} mappings
 */
MetaTemplateTemplate.prototype['mappings'] = undefined;

/**
 * @member {module:model/MetaIndexSettings} settings
 */
MetaTemplateTemplate.prototype['settings'] = undefined;






export default MetaTemplateTemplate;

