/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MetaPage model module.
 * @module model/MetaPage
 * @version 0.2.7
 */
class MetaPage {
    /**
     * Constructs a new <code>MetaPage</code>.
     * @alias module:model/MetaPage
     */
    constructor() { 
        
        MetaPage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetaPage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetaPage} obj Optional instance to populate.
     * @return {module:model/MetaPage} The populated <code>MetaPage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetaPage();

            if (data.hasOwnProperty('page_num')) {
                obj['page_num'] = ApiClient.convertToType(data['page_num'], 'Number');
            }
            if (data.hasOwnProperty('page_size')) {
                obj['page_size'] = ApiClient.convertToType(data['page_size'], 'Number');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} page_num
 */
MetaPage.prototype['page_num'] = undefined;

/**
 * @member {Number} page_size
 */
MetaPage.prototype['page_size'] = undefined;

/**
 * @member {Number} total
 */
MetaPage.prototype['total'] = undefined;






export default MetaPage;

