/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MetaIndexShard model module.
 * @module model/MetaIndexShard
 * @version 0.2.4
 */
class MetaIndexShard {
    /**
     * Constructs a new <code>MetaIndexShard</code>.
     * @alias module:model/MetaIndexShard
     */
    constructor() { 
        
        MetaIndexShard.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetaIndexShard</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetaIndexShard} obj Optional instance to populate.
     * @return {module:model/MetaIndexShard} The populated <code>MetaIndexShard</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetaIndexShard();

            if (data.hasOwnProperty('doc_num')) {
                obj['doc_num'] = ApiClient.convertToType(data['doc_num'], 'Number');
            }
            if (data.hasOwnProperty('doc_time_max')) {
                obj['doc_time_max'] = ApiClient.convertToType(data['doc_time_max'], 'Number');
            }
            if (data.hasOwnProperty('doc_time_min')) {
                obj['doc_time_min'] = ApiClient.convertToType(data['doc_time_min'], 'Number');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('storage_size')) {
                obj['storage_size'] = ApiClient.convertToType(data['storage_size'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} doc_num
 */
MetaIndexShard.prototype['doc_num'] = undefined;

/**
 * @member {Number} doc_time_max
 */
MetaIndexShard.prototype['doc_time_max'] = undefined;

/**
 * @member {Number} doc_time_min
 */
MetaIndexShard.prototype['doc_time_min'] = undefined;

/**
 * @member {Number} id
 */
MetaIndexShard.prototype['id'] = undefined;

/**
 * @member {Number} storage_size
 */
MetaIndexShard.prototype['storage_size'] = undefined;






export default MetaIndexShard;

