/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MetaShards model module.
 * @module model/MetaShards
 * @version 0.2.4
 */
class MetaShards {
    /**
     * Constructs a new <code>MetaShards</code>.
     * @alias module:model/MetaShards
     */
    constructor() { 
        
        MetaShards.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetaShards</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetaShards} obj Optional instance to populate.
     * @return {module:model/MetaShards} The populated <code>MetaShards</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetaShards();

            if (data.hasOwnProperty('failed')) {
                obj['failed'] = ApiClient.convertToType(data['failed'], 'Number');
            }
            if (data.hasOwnProperty('skipped')) {
                obj['skipped'] = ApiClient.convertToType(data['skipped'], 'Number');
            }
            if (data.hasOwnProperty('successful')) {
                obj['successful'] = ApiClient.convertToType(data['successful'], 'Number');
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} failed
 */
MetaShards.prototype['failed'] = undefined;

/**
 * @member {Number} skipped
 */
MetaShards.prototype['skipped'] = undefined;

/**
 * @member {Number} successful
 */
MetaShards.prototype['successful'] = undefined;

/**
 * @member {Number} total
 */
MetaShards.prototype['total'] = undefined;






export default MetaShards;

