/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MetaHTTPResponseTemplate model module.
 * @module model/MetaHTTPResponseTemplate
 * @version 0.2.4
 */
class MetaHTTPResponseTemplate {
    /**
     * Constructs a new <code>MetaHTTPResponseTemplate</code>.
     * @alias module:model/MetaHTTPResponseTemplate
     */
    constructor() { 
        
        MetaHTTPResponseTemplate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetaHTTPResponseTemplate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetaHTTPResponseTemplate} obj Optional instance to populate.
     * @return {module:model/MetaHTTPResponseTemplate} The populated <code>MetaHTTPResponseTemplate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetaHTTPResponseTemplate();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('template')) {
                obj['template'] = ApiClient.convertToType(data['template'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} message
 */
MetaHTTPResponseTemplate.prototype['message'] = undefined;

/**
 * @member {String} template
 */
MetaHTTPResponseTemplate.prototype['template'] = undefined;






export default MetaHTTPResponseTemplate;

