/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MetaFuzzyQuery model module.
 * @module model/MetaFuzzyQuery
 * @version 0.2.7
 */
class MetaFuzzyQuery {
    /**
     * Constructs a new <code>MetaFuzzyQuery</code>.
     * @alias module:model/MetaFuzzyQuery
     */
    constructor() { 
        
        MetaFuzzyQuery.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetaFuzzyQuery</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetaFuzzyQuery} obj Optional instance to populate.
     * @return {module:model/MetaFuzzyQuery} The populated <code>MetaFuzzyQuery</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetaFuzzyQuery();

            if (data.hasOwnProperty('boost')) {
                obj['boost'] = ApiClient.convertToType(data['boost'], 'Number');
            }
            if (data.hasOwnProperty('fuzziness')) {
                obj['fuzziness'] = ApiClient.convertToType(data['fuzziness'], Object);
            }
            if (data.hasOwnProperty('prefix_length')) {
                obj['prefix_length'] = ApiClient.convertToType(data['prefix_length'], 'Number');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} boost
 */
MetaFuzzyQuery.prototype['boost'] = undefined;

/**
 * auto, 1,2,3,n
 * @member {Object} fuzziness
 */
MetaFuzzyQuery.prototype['fuzziness'] = undefined;

/**
 * @member {Number} prefix_length
 */
MetaFuzzyQuery.prototype['prefix_length'] = undefined;

/**
 * @member {String} value
 */
MetaFuzzyQuery.prototype['value'] = undefined;






export default MetaFuzzyQuery;

