/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MetaIndexTemplate from './MetaIndexTemplate';

/**
 * The MetaTemplate model module.
 * @module model/MetaTemplate
 * @version 0.2.4
 */
class MetaTemplate {
    /**
     * Constructs a new <code>MetaTemplate</code>.
     * @alias module:model/MetaTemplate
     */
    constructor() { 
        
        MetaTemplate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetaTemplate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetaTemplate} obj Optional instance to populate.
     * @return {module:model/MetaTemplate} The populated <code>MetaTemplate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetaTemplate();

            if (data.hasOwnProperty('index_template')) {
                obj['index_template'] = MetaIndexTemplate.constructFromObject(data['index_template']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/MetaIndexTemplate} index_template
 */
MetaTemplate.prototype['index_template'] = undefined;

/**
 * @member {String} name
 */
MetaTemplate.prototype['name'] = undefined;






export default MetaTemplate;

