/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.3.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MetaHttpRetriesResponse model module.
 * @module model/MetaHttpRetriesResponse
 * @version 0.3.3
 */
class MetaHttpRetriesResponse {
    /**
     * Constructs a new <code>MetaHttpRetriesResponse</code>.
     * @alias module:model/MetaHttpRetriesResponse
     */
    constructor() { 
        
        MetaHttpRetriesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetaHttpRetriesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetaHttpRetriesResponse} obj Optional instance to populate.
     * @return {module:model/MetaHttpRetriesResponse} The populated <code>MetaHttpRetriesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetaHttpRetriesResponse();

            if (data.hasOwnProperty('bulk')) {
                obj['bulk'] = ApiClient.convertToType(data['bulk'], 'Number');
            }
            if (data.hasOwnProperty('search')) {
                obj['search'] = ApiClient.convertToType(data['search'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} bulk
 */
MetaHttpRetriesResponse.prototype['bulk'] = undefined;

/**
 * @member {Number} search
 */
MetaHttpRetriesResponse.prototype['search'] = undefined;






export default MetaHttpRetriesResponse;

