/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MetaHTTPResponseIndex model module.
 * @module model/MetaHTTPResponseIndex
 * @version 0.2.4
 */
class MetaHTTPResponseIndex {
    /**
     * Constructs a new <code>MetaHTTPResponseIndex</code>.
     * @alias module:model/MetaHTTPResponseIndex
     */
    constructor() { 
        
        MetaHTTPResponseIndex.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetaHTTPResponseIndex</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetaHTTPResponseIndex} obj Optional instance to populate.
     * @return {module:model/MetaHTTPResponseIndex} The populated <code>MetaHTTPResponseIndex</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetaHTTPResponseIndex();

            if (data.hasOwnProperty('index')) {
                obj['index'] = ApiClient.convertToType(data['index'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('storage_type')) {
                obj['storage_type'] = ApiClient.convertToType(data['storage_type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} index
 */
MetaHTTPResponseIndex.prototype['index'] = undefined;

/**
 * @member {String} message
 */
MetaHTTPResponseIndex.prototype['message'] = undefined;

/**
 * @member {String} storage_type
 */
MetaHTTPResponseIndex.prototype['storage_type'] = undefined;






export default MetaHTTPResponseIndex;

