/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1AggregationBucket from './V1AggregationBucket';

/**
 * The V1AggregationResponse model module.
 * @module model/V1AggregationResponse
 * @version 0.2.7
 */
class V1AggregationResponse {
    /**
     * Constructs a new <code>V1AggregationResponse</code>.
     * @alias module:model/V1AggregationResponse
     */
    constructor() { 
        
        V1AggregationResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1AggregationResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1AggregationResponse} obj Optional instance to populate.
     * @return {module:model/V1AggregationResponse} The populated <code>V1AggregationResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1AggregationResponse();

            if (data.hasOwnProperty('buckets')) {
                obj['buckets'] = ApiClient.convertToType(data['buckets'], [V1AggregationBucket]);
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/V1AggregationBucket>} buckets
 */
V1AggregationResponse.prototype['buckets'] = undefined;

/**
 * @member {Object} value
 */
V1AggregationResponse.prototype['value'] = undefined;






export default V1AggregationResponse;

