/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1AggregationDateRange from './V1AggregationDateRange';
import V1AggregationNumberRange from './V1AggregationNumberRange';

/**
 * The V1AggregationParams model module.
 * @module model/V1AggregationParams
 * @version 0.2.4
 */
class V1AggregationParams {
    /**
     * Constructs a new <code>V1AggregationParams</code>.
     * @alias module:model/V1AggregationParams
     */
    constructor() { 
        
        V1AggregationParams.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1AggregationParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1AggregationParams} obj Optional instance to populate.
     * @return {module:model/V1AggregationParams} The populated <code>V1AggregationParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1AggregationParams();

            if (data.hasOwnProperty('agg_type')) {
                obj['agg_type'] = ApiClient.convertToType(data['agg_type'], 'String');
            }
            if (data.hasOwnProperty('aggs')) {
                obj['aggs'] = ApiClient.convertToType(data['aggs'], {'String': V1AggregationParams});
            }
            if (data.hasOwnProperty('date_ranges')) {
                obj['date_ranges'] = ApiClient.convertToType(data['date_ranges'], [V1AggregationDateRange]);
            }
            if (data.hasOwnProperty('field')) {
                obj['field'] = ApiClient.convertToType(data['field'], 'String');
            }
            if (data.hasOwnProperty('ranges')) {
                obj['ranges'] = ApiClient.convertToType(data['ranges'], [V1AggregationNumberRange]);
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('weight_field')) {
                obj['weight_field'] = ApiClient.convertToType(data['weight_field'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} agg_type
 */
V1AggregationParams.prototype['agg_type'] = undefined;

/**
 * @member {Object.<String, module:model/V1AggregationParams>} aggs
 */
V1AggregationParams.prototype['aggs'] = undefined;

/**
 * @member {Array.<module:model/V1AggregationDateRange>} date_ranges
 */
V1AggregationParams.prototype['date_ranges'] = undefined;

/**
 * @member {String} field
 */
V1AggregationParams.prototype['field'] = undefined;

/**
 * @member {Array.<module:model/V1AggregationNumberRange>} ranges
 */
V1AggregationParams.prototype['ranges'] = undefined;

/**
 * @member {Number} size
 */
V1AggregationParams.prototype['size'] = undefined;

/**
 * Field name to be used for setting weight for primary field for weighted average aggregation
 * @member {String} weight_field
 */
V1AggregationParams.prototype['weight_field'] = undefined;






export default V1AggregationParams;

