/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1QueryParams model module.
 * @module model/V1QueryParams
 * @version 0.2.4
 */
class V1QueryParams {
    /**
     * Constructs a new <code>V1QueryParams</code>.
     * @alias module:model/V1QueryParams
     */
    constructor() { 
        
        V1QueryParams.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1QueryParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1QueryParams} obj Optional instance to populate.
     * @return {module:model/V1QueryParams} The populated <code>V1QueryParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1QueryParams();

            if (data.hasOwnProperty('boost')) {
                obj['boost'] = ApiClient.convertToType(data['boost'], 'Number');
            }
            if (data.hasOwnProperty('end_time')) {
                obj['end_time'] = ApiClient.convertToType(data['end_time'], 'String');
            }
            if (data.hasOwnProperty('field')) {
                obj['field'] = ApiClient.convertToType(data['field'], 'String');
            }
            if (data.hasOwnProperty('start_time')) {
                obj['start_time'] = ApiClient.convertToType(data['start_time'], 'String');
            }
            if (data.hasOwnProperty('term')) {
                obj['term'] = ApiClient.convertToType(data['term'], 'String');
            }
            if (data.hasOwnProperty('terms')) {
                obj['terms'] = ApiClient.convertToType(data['terms'], [['String']]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} boost
 */
V1QueryParams.prototype['boost'] = undefined;

/**
 * @member {String} end_time
 */
V1QueryParams.prototype['end_time'] = undefined;

/**
 * @member {String} field
 */
V1QueryParams.prototype['field'] = undefined;

/**
 * @member {String} start_time
 */
V1QueryParams.prototype['start_time'] = undefined;

/**
 * @member {String} term
 */
V1QueryParams.prototype['term'] = undefined;

/**
 * For multi phrase query
 * @member {Array.<Array.<String>>} terms
 */
V1QueryParams.prototype['terms'] = undefined;






export default V1QueryParams;

