/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V1QueryHighlight model module.
 * @module model/V1QueryHighlight
 * @version 0.2.4
 */
class V1QueryHighlight {
    /**
     * Constructs a new <code>V1QueryHighlight</code>.
     * @alias module:model/V1QueryHighlight
     */
    constructor() { 
        
        V1QueryHighlight.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1QueryHighlight</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1QueryHighlight} obj Optional instance to populate.
     * @return {module:model/V1QueryHighlight} The populated <code>V1QueryHighlight</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1QueryHighlight();

            if (data.hasOwnProperty('fields')) {
                obj['fields'] = ApiClient.convertToType(data['fields'], ['String']);
            }
            if (data.hasOwnProperty('style')) {
                obj['style'] = ApiClient.convertToType(data['style'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} fields
 */
V1QueryHighlight.prototype['fields'] = undefined;

/**
 * @member {String} style
 */
V1QueryHighlight.prototype['style'] = undefined;






export default V1QueryHighlight;

