/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V1AggregationResponse from './V1AggregationResponse';
import V1Hits from './V1Hits';

/**
 * The V1SearchResponse model module.
 * @module model/V1SearchResponse
 * @version 0.2.4
 */
class V1SearchResponse {
    /**
     * Constructs a new <code>V1SearchResponse</code>.
     * @alias module:model/V1SearchResponse
     */
    constructor() { 
        
        V1SearchResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V1SearchResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V1SearchResponse} obj Optional instance to populate.
     * @return {module:model/V1SearchResponse} The populated <code>V1SearchResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V1SearchResponse();

            if (data.hasOwnProperty('aggregations')) {
                obj['aggregations'] = ApiClient.convertToType(data['aggregations'], {'String': V1AggregationResponse});
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('hits')) {
                obj['hits'] = V1Hits.constructFromObject(data['hits']);
            }
            if (data.hasOwnProperty('timed_out')) {
                obj['timed_out'] = ApiClient.convertToType(data['timed_out'], 'Boolean');
            }
            if (data.hasOwnProperty('took')) {
                obj['took'] = ApiClient.convertToType(data['took'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Object.<String, module:model/V1AggregationResponse>} aggregations
 */
V1SearchResponse.prototype['aggregations'] = undefined;

/**
 * @member {String} error
 */
V1SearchResponse.prototype['error'] = undefined;

/**
 * @member {module:model/V1Hits} hits
 */
V1SearchResponse.prototype['hits'] = undefined;

/**
 * @member {Boolean} timed_out
 */
V1SearchResponse.prototype['timed_out'] = undefined;

/**
 * Time it took to generate the response
 * @member {Number} took
 */
V1SearchResponse.prototype['took'] = undefined;






export default V1SearchResponse;

