/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import MetaHealthzResponse from '../model/MetaHealthzResponse';
import MetaVersionResponse from '../model/MetaVersionResponse';

/**
* Default service.
* @module api/Default
* @version 0.2.7
*/
export default class Default {

    /**
    * Constructs a new Default. 
    * @alias module:api/Default
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the healthz operation.
     * @callback module:api/Default~healthzCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MetaHealthzResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get healthz
     * @param {module:api/Default~healthzCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MetaHealthzResponse}
     */
    healthz(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = MetaHealthzResponse;
      return this.apiClient.callApi(
        '/healthz', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the version operation.
     * @callback module:api/Default~versionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MetaVersionResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get version
     * @param {module:api/Default~versionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MetaVersionResponse}
     */
    version(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = MetaVersionResponse;
      return this.apiClient.callApi(
        '/version', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
