/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ZincSearchSDK);
  }
}(this, function(expect, ZincSearchSDK) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ZincSearchSDK.CoreIndex();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CoreIndex', function() {
    it('should create an instance of CoreIndex', function() {
      // uncomment below and update the code to test CoreIndex
      //var instance = new ZincSearchSDK.CoreIndex();
      //expect(instance).to.be.a(ZincSearchSDK.CoreIndex);
    });

    it('should have the property createAt (base name: "create_at")', function() {
      // uncomment below and update the code to test the property createAt
      //var instance = new ZincSearchSDK.CoreIndex();
      //expect(instance).to.be();
    });

    it('should have the property docNum (base name: "doc_num")', function() {
      // uncomment below and update the code to test the property docNum
      //var instance = new ZincSearchSDK.CoreIndex();
      //expect(instance).to.be();
    });

    it('should have the property docTimeMax (base name: "doc_time_max")', function() {
      // uncomment below and update the code to test the property docTimeMax
      //var instance = new ZincSearchSDK.CoreIndex();
      //expect(instance).to.be();
    });

    it('should have the property docTimeMin (base name: "doc_time_min")', function() {
      // uncomment below and update the code to test the property docTimeMin
      //var instance = new ZincSearchSDK.CoreIndex();
      //expect(instance).to.be();
    });

    it('should have the property mappings (base name: "mappings")', function() {
      // uncomment below and update the code to test the property mappings
      //var instance = new ZincSearchSDK.CoreIndex();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new ZincSearchSDK.CoreIndex();
      //expect(instance).to.be();
    });

    it('should have the property settings (base name: "settings")', function() {
      // uncomment below and update the code to test the property settings
      //var instance = new ZincSearchSDK.CoreIndex();
      //expect(instance).to.be();
    });

    it('should have the property shardNum (base name: "shard_num")', function() {
      // uncomment below and update the code to test the property shardNum
      //var instance = new ZincSearchSDK.CoreIndex();
      //expect(instance).to.be();
    });

    it('should have the property shards (base name: "shards")', function() {
      // uncomment below and update the code to test the property shards
      //var instance = new ZincSearchSDK.CoreIndex();
      //expect(instance).to.be();
    });

    it('should have the property storageSize (base name: "storage_size")', function() {
      // uncomment below and update the code to test the property storageSize
      //var instance = new ZincSearchSDK.CoreIndex();
      //expect(instance).to.be();
    });

    it('should have the property storageType (base name: "storage_type")', function() {
      // uncomment below and update the code to test the property storageType
      //var instance = new ZincSearchSDK.CoreIndex();
      //expect(instance).to.be();
    });

    it('should have the property updateAt (base name: "update_at")', function() {
      // uncomment below and update the code to test the property updateAt
      //var instance = new ZincSearchSDK.CoreIndex();
      //expect(instance).to.be();
    });

  });

}));
