/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ZincSearchSDK);
  }
}(this, function(expect, ZincSearchSDK) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ZincSearchSDK.MetaHit();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MetaHit', function() {
    it('should create an instance of MetaHit', function() {
      // uncomment below and update the code to test MetaHit
      //var instance = new ZincSearchSDK.MetaHit();
      //expect(instance).to.be.a(ZincSearchSDK.MetaHit);
    });

    it('should have the property timestamp (base name: "@timestamp")', function() {
      // uncomment below and update the code to test the property timestamp
      //var instance = new ZincSearchSDK.MetaHit();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ZincSearchSDK.MetaHit();
      //expect(instance).to.be();
    });

    it('should have the property index (base name: "_index")', function() {
      // uncomment below and update the code to test the property index
      //var instance = new ZincSearchSDK.MetaHit();
      //expect(instance).to.be();
    });

    it('should have the property score (base name: "_score")', function() {
      // uncomment below and update the code to test the property score
      //var instance = new ZincSearchSDK.MetaHit();
      //expect(instance).to.be();
    });

    it('should have the property source (base name: "_source")', function() {
      // uncomment below and update the code to test the property source
      //var instance = new ZincSearchSDK.MetaHit();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "_type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new ZincSearchSDK.MetaHit();
      //expect(instance).to.be();
    });

    it('should have the property fields (base name: "fields")', function() {
      // uncomment below and update the code to test the property fields
      //var instance = new ZincSearchSDK.MetaHit();
      //expect(instance).to.be();
    });

    it('should have the property highlight (base name: "highlight")', function() {
      // uncomment below and update the code to test the property highlight
      //var instance = new ZincSearchSDK.MetaHit();
      //expect(instance).to.be();
    });

  });

}));
