/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ZincSearchSDK);
  }
}(this, function(expect, ZincSearchSDK) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ZincSearchSDK.MetaMultiMatchQuery();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MetaMultiMatchQuery', function() {
    it('should create an instance of MetaMultiMatchQuery', function() {
      // uncomment below and update the code to test MetaMultiMatchQuery
      //var instance = new ZincSearchSDK.MetaMultiMatchQuery();
      //expect(instance).to.be.a(ZincSearchSDK.MetaMultiMatchQuery);
    });

    it('should have the property analyzer (base name: "analyzer")', function() {
      // uncomment below and update the code to test the property analyzer
      //var instance = new ZincSearchSDK.MetaMultiMatchQuery();
      //expect(instance).to.be();
    });

    it('should have the property boost (base name: "boost")', function() {
      // uncomment below and update the code to test the property boost
      //var instance = new ZincSearchSDK.MetaMultiMatchQuery();
      //expect(instance).to.be();
    });

    it('should have the property fields (base name: "fields")', function() {
      // uncomment below and update the code to test the property fields
      //var instance = new ZincSearchSDK.MetaMultiMatchQuery();
      //expect(instance).to.be();
    });

    it('should have the property minimumShouldMatch (base name: "minimum_should_match")', function() {
      // uncomment below and update the code to test the property minimumShouldMatch
      //var instance = new ZincSearchSDK.MetaMultiMatchQuery();
      //expect(instance).to.be();
    });

    it('should have the property operator (base name: "operator")', function() {
      // uncomment below and update the code to test the property operator
      //var instance = new ZincSearchSDK.MetaMultiMatchQuery();
      //expect(instance).to.be();
    });

    it('should have the property query (base name: "query")', function() {
      // uncomment below and update the code to test the property query
      //var instance = new ZincSearchSDK.MetaMultiMatchQuery();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new ZincSearchSDK.MetaMultiMatchQuery();
      //expect(instance).to.be();
    });

  });

}));
