/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ZincSearchSDK);
  }
}(this, function(expect, ZincSearchSDK) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ZincSearchSDK.MetaVersionResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MetaVersionResponse', function() {
    it('should create an instance of MetaVersionResponse', function() {
      // uncomment below and update the code to test MetaVersionResponse
      //var instance = new ZincSearchSDK.MetaVersionResponse();
      //expect(instance).to.be.a(ZincSearchSDK.MetaVersionResponse);
    });

    it('should have the property branch (base name: "branch")', function() {
      // uncomment below and update the code to test the property branch
      //var instance = new ZincSearchSDK.MetaVersionResponse();
      //expect(instance).to.be();
    });

    it('should have the property build (base name: "build")', function() {
      // uncomment below and update the code to test the property build
      //var instance = new ZincSearchSDK.MetaVersionResponse();
      //expect(instance).to.be();
    });

    it('should have the property buildDate (base name: "build_date")', function() {
      // uncomment below and update the code to test the property buildDate
      //var instance = new ZincSearchSDK.MetaVersionResponse();
      //expect(instance).to.be();
    });

    it('should have the property commitHash (base name: "commit_hash")', function() {
      // uncomment below and update the code to test the property commitHash
      //var instance = new ZincSearchSDK.MetaVersionResponse();
      //expect(instance).to.be();
    });

    it('should have the property version (base name: "version")', function() {
      // uncomment below and update the code to test the property version
      //var instance = new ZincSearchSDK.MetaVersionResponse();
      //expect(instance).to.be();
    });

  });

}));
