/**
 * Zinc Search engine API
 * Zinc Search engine API documents https://docs.zincsearch.com
 *
 * The version of the OpenAPI document: 0.2.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ZincSearchSDK);
  }
}(this, function(expect, ZincSearchSDK) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ZincSearchSDK.MetaAggregations();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MetaAggregations', function() {
    it('should create an instance of MetaAggregations', function() {
      // uncomment below and update the code to test MetaAggregations
      //var instance = new ZincSearchSDK.MetaAggregations();
      //expect(instance).to.be.a(ZincSearchSDK.MetaAggregations);
    });

    it('should have the property aggs (base name: "aggs")', function() {
      // uncomment below and update the code to test the property aggs
      //var instance = new ZincSearchSDK.MetaAggregations();
      //expect(instance).to.be();
    });

    it('should have the property autoDateHistogram (base name: "auto_date_histogram")', function() {
      // uncomment below and update the code to test the property autoDateHistogram
      //var instance = new ZincSearchSDK.MetaAggregations();
      //expect(instance).to.be();
    });

    it('should have the property avg (base name: "avg")', function() {
      // uncomment below and update the code to test the property avg
      //var instance = new ZincSearchSDK.MetaAggregations();
      //expect(instance).to.be();
    });

    it('should have the property cardinality (base name: "cardinality")', function() {
      // uncomment below and update the code to test the property cardinality
      //var instance = new ZincSearchSDK.MetaAggregations();
      //expect(instance).to.be();
    });

    it('should have the property count (base name: "count")', function() {
      // uncomment below and update the code to test the property count
      //var instance = new ZincSearchSDK.MetaAggregations();
      //expect(instance).to.be();
    });

    it('should have the property dateHistogram (base name: "date_histogram")', function() {
      // uncomment below and update the code to test the property dateHistogram
      //var instance = new ZincSearchSDK.MetaAggregations();
      //expect(instance).to.be();
    });

    it('should have the property dateRange (base name: "date_range")', function() {
      // uncomment below and update the code to test the property dateRange
      //var instance = new ZincSearchSDK.MetaAggregations();
      //expect(instance).to.be();
    });

    it('should have the property histogram (base name: "histogram")', function() {
      // uncomment below and update the code to test the property histogram
      //var instance = new ZincSearchSDK.MetaAggregations();
      //expect(instance).to.be();
    });

    it('should have the property ipRange (base name: "ip_range")', function() {
      // uncomment below and update the code to test the property ipRange
      //var instance = new ZincSearchSDK.MetaAggregations();
      //expect(instance).to.be();
    });

    it('should have the property max (base name: "max")', function() {
      // uncomment below and update the code to test the property max
      //var instance = new ZincSearchSDK.MetaAggregations();
      //expect(instance).to.be();
    });

    it('should have the property min (base name: "min")', function() {
      // uncomment below and update the code to test the property min
      //var instance = new ZincSearchSDK.MetaAggregations();
      //expect(instance).to.be();
    });

    it('should have the property range (base name: "range")', function() {
      // uncomment below and update the code to test the property range
      //var instance = new ZincSearchSDK.MetaAggregations();
      //expect(instance).to.be();
    });

    it('should have the property sum (base name: "sum")', function() {
      // uncomment below and update the code to test the property sum
      //var instance = new ZincSearchSDK.MetaAggregations();
      //expect(instance).to.be();
    });

    it('should have the property terms (base name: "terms")', function() {
      // uncomment below and update the code to test the property terms
      //var instance = new ZincSearchSDK.MetaAggregations();
      //expect(instance).to.be();
    });

    it('should have the property weightedAvg (base name: "weighted_avg")', function() {
      // uncomment below and update the code to test the property weightedAvg
      //var instance = new ZincSearchSDK.MetaAggregations();
      //expect(instance).to.be();
    });

  });

}));
